<html>
<body>
	<h1 style="color: BLUE; font-size: 65px;" align="left"> HI IAM BHASKAR A "DEVOPS ENGINEER" PART OF DEVOPS MINDCIRCUIT INSTITUTE,THANK YOU MADHU SIR FOR YOUR MARVELLOUS TEACHING</h1>
</body>
</html>
